# Generated by Django 4.2.7 on 2023-12-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='opinion',
        ),
    ]
