# Generated by Django 4.2.7 on 2023-12-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_destino_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rubro', models.CharField(max_length=30)),
                ('calificacion', models.IntegerField()),
            ],
        ),
    ]
