# Generated by Django 4.2.7 on 2023-12-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_establecimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
