# Generated by Django 4.2.7 on 2023-12-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_delete_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
